sample_rate: 16000
log_prediction: false
ctc_reduction: mean_volume
skip_nan_grad: false
model_defaults:
  enc_hidden: 1024
  pred_hidden: 640
  joint_hidden: 640
train_ds:
  manifest_filepath: /disk1/NVIDIA/datasets/LibriSpeech_NeMo/librivox-train-all.json
  sample_rate: 16000
  batch_size: 16
  shuffle: true
  num_workers: 8
  pin_memory: true
  use_start_end_token: false
  trim_silence: false
  max_duration: 16.7
  min_duration: 0.1
  is_tarred: false
  tarred_audio_filepaths: null
  shuffle_n: 2048
  bucketing_strategy: fully_randomized
  bucketing_batch_size: null
validation_ds:
  manifest_filepath: /disk1/NVIDIA/datasets/LibriSpeech_NeMo/librivox-dev-clean.json
  sample_rate: 16000
  batch_size: 16
  shuffle: false
  use_start_end_token: false
  num_workers: 8
  pin_memory: true
test_ds:
  manifest_filepath: null
  sample_rate: 16000
  batch_size: 16
  shuffle: false
  use_start_end_token: false
  num_workers: 8
  pin_memory: true
tokenizer:
  dir: /disk3/datasets/suno_asr_set3_tokenizer/tokenizer_spe_bpe_v1024/
  type: bpe
  model_path: nemo:2e2b4c0cc6bd44d9a379f769249666ae_tokenizer.model
  vocab_path: nemo:248b67f0680446e28a2f445da319615a_vocab.txt
  spe_tokenizer_vocab: nemo:ad13e916727a444097e043d5744eaf63_tokenizer.vocab
preprocessor:
  _target_: nemo.collections.asr.modules.AudioToMelSpectrogramPreprocessor
  sample_rate: 16000
  normalize: per_feature
  window_size: 0.025
  window_stride: 0.01
  window: hann
  features: 80
  n_fft: 512
  log: true
  frame_splicing: 1
  dither: 1.0e-05
  pad_to: 16
  pad_value: 0.0
spec_augment:
  _target_: nemo.collections.asr.modules.SpectrogramAugmentation
  freq_masks: 2
  time_masks: 10
  freq_width: 27
  time_width: 0.05
encoder:
  _target_: nemo.collections.asr.modules.ConformerEncoder
  feat_in: 80
  feat_out: -1
  n_layers: 24
  d_model: 1024
  subsampling: dw_striding
  subsampling_factor: 8
  subsampling_conv_channels: 256
  causal_downsampling: false
  ff_expansion_factor: 4
  self_attention_model: rel_pos
  n_heads: 8
  att_context_size:
  - -1
  - -1
  att_context_style: regular
  xscaling: true
  untie_biases: true
  pos_emb_max_len: 5000
  conv_kernel_size: 9
  conv_norm_type: batch_norm
  conv_context_size: null
  dropout: 0.1
  dropout_pre_encoder: 0.1
  dropout_emb: 0.0
  dropout_att: 0.1
  stochastic_depth_drop_prob: 0.0
  stochastic_depth_mode: linear
  stochastic_depth_start_layer: 1
decoder:
  _target_: nemo.collections.asr.modules.ConvASRDecoder
  feat_in: 1024
  num_classes: 1024
  vocabulary:
  - <unk>
  - ▁t
  - ▁th
  - ▁a
  - ▁i
  - ▁the
  - re
  - ▁w
  - ▁s
  - ▁o
  - in
  - at
  - er
  - ou
  - nd
  - ▁c
  - ▁b
  - ▁h
  - 'on'
  - ▁m
  - ▁f
  - ing
  - ▁to
  - en
  - ▁p
  - ▁and
  - ▁d
  - es
  - or
  - an
  - ll
  - ▁y
  - ▁l
  - ed
  - ▁of
  - ▁in
  - it
  - is
  - ▁you
  - ▁that
  - ar
  - ▁g
  - ▁n
  - as
  - om
  - ▁it
  - ic
  - ve
  - ▁e
  - ▁wh
  - ▁be
  - us
  - le
  - al
  - ion
  - ow
  - ▁we
  - ▁re
  - ▁is
  - ut
  - ot
  - ent
  - ▁on
  - et
  - ▁ha
  - ay
  - ct
  - ▁he
  - id
  - ▁for
  - ▁st
  - ver
  - ly
  - ro
  - ig
  - ▁so
  - ld
  - ▁this
  - ke
  - ▁u
  - se
  - all
  - st
  - ur
  - ce
  - ch
  - im
  - ith
  - ▁as
  - ▁k
  - ▁an
  - ▁was
  - ▁j
  - ▁with
  - ir
  - ▁go
  - ra
  - ▁do
  - ▁have
  - ▁li
  - ▁sh
  - ▁se
  - ▁they
  - ▁are
  - am
  - ht
  - ▁but
  - ation
  - ▁not
  - th
  - ▁r
  - ally
  - ad
  - ust
  - ▁or
  - ▁com
  - ould
  - ▁can
  - ill
  - ▁ne
  - ight
  - ▁ch
  - ▁de
  - ▁con
  - ▁at
  - ▁mo
  - ant
  - oo
  - il
  - ▁me
  - ▁what
  - ▁there
  - ter
  - pe
  - ▁ab
  - ▁su
  - ere
  - ck
  - ▁pro
  - ▁al
  - ▁fr
  - ▁kn
  - ▁all
  - ers
  - ▁like
  - ge
  - ▁ex
  - ▁som
  - ul
  - ▁your
  - ▁v
  - pp
  - use
  - ▁if
  - ess
  - ate
  - est
  - ▁know
  - out
  - if
  - ▁just
  - ment
  - qu
  - op
  - ain
  - ▁one
  - ol
  - ri
  - art
  - very
  - ▁wor
  - ive
  - ist
  - ▁my
  - nt
  - ab
  - ▁from
  - ort
  - ▁ma
  - ▁about
  - res
  - ity
  - ▁out
  - ▁bec
  - ▁le
  - our
  - od
  - and
  - ink
  - ie
  - ▁up
  - ind
  - os
  - un
  - ause
  - oug
  - um
  - ▁some
  - ▁int
  - ▁by
  - ▁pl
  - ▁get
  - el
  - ard
  - ▁when
  - ▁don
  - her
  - ▁will
  - ▁us
  - ▁would
  - ook
  - ies
  - ich
  - ▁because
  - ▁think
  - em
  - ▁pe
  - ▁his
  - ack
  - ▁then
  - ▁our
  - ide
  - ▁tim
  - ▁how
  - ven
  - ▁tr
  - ▁who
  - ▁them
  - ure
  - ▁ar
  - ▁ye
  - ▁more
  - ▁going
  - ect
  - ▁sa
  - ▁cl
  - ▁had
  - ▁now
  - ▁which
  - ▁here
  - ous
  - ▁their
  - ▁tw
  - so
  - ▁has
  - ud
  - ▁co
  - ▁ta
  - ound
  - ▁were
  - ast
  - ▁peop
  - ough
  - ▁no
  - ▁really
  - ▁any
  - ▁people
  - ▁want
  - ▁she
  - ▁en
  - ▁fa
  - ▁te
  - ame
  - ine
  - ▁qu
  - red
  - ▁im
  - ▁right
  - ther
  - ▁act
  - ▁thing
  - king
  - ose
  - ▁ad
  - ▁see
  - ▁time
  - ▁these
  - ci
  - one
  - ▁say
  - ▁also
  - ▁fe
  - per
  - ▁ag
  - ▁man
  - ore
  - ▁un
  - pt
  - ▁her
  - ▁look
  - ong
  - ice
  - ▁very
  - ff
  - ions
  - ▁comp
  - ▁did
  - itt
  - ▁well
  - ▁other
  - iv
  - ase
  - ree
  - hing
  - ▁lo
  - reat
  - ▁cont
  - ▁part
  - ▁into
  - nder
  - ▁been
  - are
  - ▁am
  - ans
  - ▁sp
  - ▁two
  - ue
  - ▁way
  - age
  - ▁where
  - ite
  - ▁dis
  - ▁than
  - ▁every
  - ▁pr
  - ▁po
  - ag
  - ▁need
  - ach
  - iff
  - ence
  - pl
  - own
  - ▁ac
  - ble
  - ▁over
  - iz
  - ▁work
  - ▁res
  - ▁make
  - ▁could
  - ▁off
  - ually
  - ▁ro
  - ▁back
  - able
  - ip
  - ry
  - ▁him
  - ▁cour
  - ber
  - ▁pre
  - ▁fir
  - ▁spe
  - ap
  - ars
  - ▁diff
  - ire
  - ▁somet
  - ▁imp
  - ▁those
  - ▁comm
  - ance
  - ick
  - ▁even
  - ated
  - way
  - sel
  - ▁let
  - ▁br
  - ty
  - ▁per
  - int
  - ▁first
  - ▁thr
  - ▁under
  - ah
  - ▁may
  - ▁cou
  - ▁new
  - ress
  - act
  - ▁gr
  - ep
  - ▁said
  - ations
  - ▁good
  - ace
  - ass
  - ▁does
  - orm
  - ish
  - ▁af
  - ving
  - co
  - ▁app
  - ▁lot
  - ▁things
  - ▁tra
  - ittle
  - ▁bl
  - ▁little
  - ▁mu
  - cess
  - fe
  - ome
  - ▁inc
  - ▁differe
  - ary
  - ical
  - ▁only
  - ult
  - ▁again
  - ▁got
  - ens
  - ▁gu
  - ▁kind
  - ▁much
  - ord
  - ▁through
  - ition
  - ild
  - ▁down
  - ▁actually
  - ▁something
  - ang
  - ru
  - ces
  - ▁fl
  - ile
  - ater
  - ▁ra
  - ▁take
  - ict
  - ign
  - ▁sc
  - vel
  - ▁bet
  - ▁tal
  - ▁yeah
  - ▁use
  - fore
  - ▁bu
  - ▁start
  - ory
  - be
  - ▁day
  - wn
  - xt
  - ia
  - ak
  - ▁after
  - ▁should
  - ▁fo
  - ▁ho
  - ▁hel
  - ▁ind
  - ▁uh
  - na
  - ial
  - other
  - ▁ke
  - ▁call
  - ▁most
  - ▁ok
  - ▁different
  - ▁em
  - ting
  - ple
  - ▁being
  - ▁bo
  - ning
  - ▁too
  - ors
  - ▁happ
  - ark
  - og
  - ▁help
  - ▁rem
  - du
  - ction
  - ood
  - ▁ser
  - ether
  - ious
  - ▁mean
  - ▁many
  - ▁court
  - ▁bel
  - ade
  - ▁la
  - ved
  - ▁des
  - ▁rec
  - ▁jo
  - ▁dec
  - ves
  - ▁before
  - ▁put
  - self
  - ▁point
  - te
  - ▁ev
  - form
  - ents
  - ▁add
  - ody
  - thing
  - ▁case
  - ▁pers
  - ▁cons
  - iss
  - ▁three
  - oth
  - ▁ph
  - ▁come
  - ▁find
  - ▁why
  - ull
  - ▁show
  - ▁bas
  - ▁great
  - ily
  - ▁rel
  - ▁sm
  - ▁its
  - ▁fact
  - ▁pos
  - ool
  - ments
  - ise
  - nds
  - ys
  - ▁try
  - ual
  - ful
  - erm
  - ▁inter
  - ons
  - ▁quest
  - ▁sub
  - we
  - vers
  - ▁supp
  - ▁feel
  - ▁same
  - ub
  - ates
  - urn
  - ert
  - ▁inv
  - day
  - ▁rep
  - igh
  - ▁sy
  - ▁inst
  - ▁long
  - ▁still
  - ▁okay
  - ft
  - ific
  - atch
  - ought
  - ath
  - ▁own
  - ▁made
  - ix
  - ced
  - ks
  - lic
  - ▁wr
  - de
  - ▁cr
  - ▁att
  - ▁ob
  - ▁world
  - ▁sure
  - ward
  - ▁bit
  - ▁life
  - ▁person
  - ▁pres
  - ph
  - ▁vide
  - ▁reg
  - ▁end
  - ject
  - ange
  - ▁fin
  - ied
  - pect
  - ▁didn
  - ▁around
  - ian
  - ▁car
  - ible
  - ▁sim
  - ever
  - ▁sch
  - ating
  - ▁pol
  - ▁set
  - ▁oh
  - cy
  - ▁real
  - ▁import
  - ▁count
  - ▁um
  - ▁next
  - cial
  - les
  - ▁hu
  - ▁acc
  - ▁might
  - ▁ent
  - ▁doing
  - ▁ins
  - ▁gen
  - ▁play
  - ▁cle
  - ▁another
  - ady
  - ular
  - ib
  - ways
  - ered
  - ility
  - ities
  - ▁op
  - ▁def
  - ▁years
  - ▁never
  - ower
  - ram
  - ▁tell
  - ▁sl
  - onna
  - ail
  - ren
  - ute
  - ▁gonna
  - ▁big
  - ▁give
  - der
  - ount
  - ▁ap
  - kes
  - ▁state
  - ▁cor
  - ▁min
  - ically
  - ▁mon
  - ▁fam
  - ▁important
  - ▁always
  - ▁high
  - ▁four
  - ▁gra
  - ▁ca
  - ▁stud
  - ▁dist
  - ▁talk
  - ▁num
  - ▁str
  - ▁today
  - ract
  - ▁while
  - ason
  - ▁iss
  - ▁sur
  - ▁char
  - ▁last
  - oy
  - ited
  - ▁exper
  - ▁place
  - ▁tri
  - ▁ear
  - ▁belie
  - ▁able
  - ▁underst
  - ▁che
  - ▁both
  - ug
  - ▁doesn
  - ▁keep
  - ▁happen
  - ings
  - iew
  - ather
  - ▁ass
  - ▁love
  - ative
  - av
  - ▁yes
  - ▁ele
  - ▁year
  - ▁such
  - ▁video
  - ness
  - ▁el
  - ▁trans
  - ▁five
  - ▁produ
  - ave
  - erest
  - als
  - body
  - cus
  - ▁found
  - atter
  - ▁eff
  - ▁god
  - ▁used
  - llow
  - ▁interest
  - ▁question
  - hip
  - ▁bus
  - ▁ask
  - ▁exam
  - ▁prov
  - lud
  - ▁form
  - ▁law
  - ense
  - ▁child
  - ▁gl
  - ne
  - ▁each
  - ▁understand
  - ▁care
  - stem
  - ▁med
  - ▁maybe
  - ably
  - ▁det
  - ▁coll
  - its
  - ▁commun
  - ▁hand
  - ▁'
  - ▁ref
  - ▁lear
  - ▁done
  - ▁gener
  - vern
  - ▁mr
  - ween
  - ▁better
  - ▁between
  - li
  - blem
  - ▁system
  - ertain
  - ▁school
  - ▁eas
  - ▁exp
  - ▁war
  - ention
  - ▁ty
  - ▁govern
  - ues
  - ▁problem
  - ▁plan
  - ac
  - ▁conf
  - ▁course
  - ouse
  - ▁mar
  - ▁stand
  - ▁sk
  - ▁seco
  - uring
  - ▁ed
  - ▁mem
  - ros
  - cri
  - ▁thought
  - cept
  - ▁partic
  - ▁test
  - olog
  - iness
  - ▁far
  - led
  - ▁col
  - ▁looking
  - ▁read
  - ▁whether
  - ▁word
  - me
  - ▁once
  - ize
  - ▁home
  - ▁requ
  - gg
  - ▁ide
  - ▁thank
  - ures
  - ▁called
  - ▁cur
  - ▁water
  - ▁frie
  - ▁side
  - ▁best
  - ▁number
  - oney
  - ▁turn
  - ock
  - ▁eng
  - ▁top
  - ▁open
  - ead
  - ▁everything
  - ▁term
  - ▁prob
  - ▁hard
  - ▁fun
  - ▁spec
  - ▁dire
  - ▁second
  - ▁pa
  - ▁build
  - ▁run
  - ▁sign
  - ▁reason
  - ▁inform
  - ▁watch
  - ution
  - ▁few
  - mo
  - ▁hum
  - ision
  - ▁ext
  - ▁tog
  - ▁conc
  - ▁thous
  - ▁thousand
  - ▁support
  - ▁together
  - ▁six
  - ps
  - ▁mark
  - ics
  - ▁includ
  - ef
  - ▁opp
  - ident
  - ▁anything
  - ▁met
  - ▁bre
  - ▁jud
  - ▁away
  - ▁old
  - ▁prog
  - ten
  - ▁book
  - ▁says
  - ▁seem
  - ▁contin
  - ▁process
  - ▁sing
  - ▁money
  - ▁having
  - ▁beg
  - ▁comple
  - ▁thir
  - ▁using
  - ▁ret
  - ger
  - ▁head
  - ▁cre
  - ▁poss
  - enty
  - ▁certain
  - ▁clear
  - ines
  - ▁wee
  - arch
  - ▁inf
  - ont
  - ▁sit
  - ▁lead
  - alth
  - ▁art
  - ross
  - ▁pub
  - ▁without
  - ▁pret
  - ▁getting
  - ient
  - ▁z
  - ▁wom
  - ▁power
  - ational
  - ner
  - ▁rest
  - ▁believe
  - ▁wa
  - ▁aut
  - ▁move
  - aim
  - ▁sort
  - idence
  - ▁creat
  - ▁expl
  - ▁name
  - ▁went
  - ▁eu
  - ▁change
  - ▁came
  - ▁pay
  - ices
  - ▁sin
  - ▁pur
  - ▁pass
  - ▁whole
  - ▁house
  - ▁hund
  - ▁hundred
  - ▁pretty
  - ▁trying
  - ▁ple
  - ▁allow
  - ▁compan
  - ▁government
  - ▁small
  - ▁light
  - ▁bra
  - ▁stu
  - aint
  - ▁ah
  - ▁prot
  - ets
  - ▁cent
  - velop
  - ▁family
  - ▁business
  - ety
  - ▁making
  - ▁list
  - ▁experi
  - eric
  - ▁follow
  - ately
  - ▁probably
  - ▁appe
  - ▁serv
  - ▁val
  - ▁leg
  - ▁resp
  - ▁develop
  - ready
  - ▁already
  - ▁sec
  - ell
  - ▁saying
  - ash
  - ▁hear
  - ▁loc
  - ▁adv
  - ▁pri
  - ret
  - ▁lar
  - ▁beh
  - ▁must
  - ▁hon
  - ▁means
  - ew
  - ▁par
  - ▁order
  - ▁mom
  - gn
  - ▁though
  - ▁record
  - ▁miss
  - ▁dr
  - ▁es
  - ▁eight
  - ▁ever
  - ▁left
  - ▁example
  - ▁enough
  - osed
  - ▁claim
  - ank
  - con
  - ▁americ
  - ▁information
  - ▁arg
  - ▁full
  - nce
  - ▁consid
  - ▁working
  - ature
  - ▁
  - e
  - t
  - a
  - o
  - i
  - 'n'
  - s
  - r
  - h
  - l
  - d
  - u
  - c
  - m
  - 'y'
  - w
  - g
  - f
  - p
  - b
  - v
  - k
  - ''''
  - j
  - x
  - q
  - z
interctc:
  loss_weights: []
  apply_at_layers: []
optim:
  name: adamw
  lr: 0.001
  betas:
  - 0.9
  - 0.98
  weight_decay: 0.001
  sched:
    name: CosineAnnealing
    warmup_steps: 15000
    warmup_ratio: null
    min_lr: 0.0001
target: nemo.collections.asr.models.ctc_bpe_models.EncDecCTCModelBPE
nemo_version: 1.19.0rc0
decoding:
  strategy: greedy_batch
  preserve_alignments: null
  compute_timestamps: null
  word_seperator: ' '
  ctc_timestamp_type: all
  batch_dim_index: 0
  greedy:
    preserve_alignments: false
    compute_timestamps: false
    preserve_frame_confidence: false
    confidence_method_cfg: null
  beam:
    beam_size: 4
    search_type: default
    preserve_alignments: false
    compute_timestamps: false
    return_best_hypothesis: true
    beam_alpha: 1.0
    beam_beta: 0.0
    kenlm_path: null
    flashlight_cfg:
      lexicon_path: null
      boost_path: null
      beam_size_token: 16
      beam_threshold: 20.0
      unk_weight: -.inf
      sil_weight: 0.0
    pyctcdecode_cfg:
      beam_prune_logp: -10.0
      token_min_logp: -5.0
      prune_history: false
      hotwords: null
      hotword_weight: 10.0
  confidence_cfg:
    preserve_frame_confidence: false
    preserve_token_confidence: false
    preserve_word_confidence: false
    exclude_blank: true
    aggregation: min
    method_cfg:
      name: entropy
      entropy_type: tsallis
      temperature: 0.33
      entropy_norm: exp
  temperature: 1.0
